### ISSUE TITLE
File is MISSING

### ISSUE THREAD

**Issue by Gops0** [uditbhaskar/Whizzz-The-ChatApp#2]
fragments.APIService file is missing
and also activity_forget_password layout,
Please provide it

**Comment by uditbhaskar** [comment]
I'll try to update the code soon. Hope that helps.

**Comment by uditbhaskar** [comment]
Hello Gops0,

I have updated the code with the required files. Hope it helps.

**Comment by Gops0** [comment]
Thanks bro.
