### ISSUE TITLE
My Database is not working.

### ISSUE THREAD

**Issue by AjeetMakvana** [uditbhaskar/Whizzz-The-ChatApp#5]
The Layout of the full app is working , but the database is not working properly.

It's not updating.

So , how can i properly enable the firebase database.
Please help , i am new to android development.

**Comment by uditbhaskar** [comment]
You need to implement firebase by adding dependency and then adding your app to firebase console. You must sign in with your Google account. For reference check firebase tutorial on youtube.

**Comment by AjeetMakvana** [comment]
But , do i need to add any code for firebase realtime database ?

I already added my project and dependencies for firebase.

**Comment by uditbhaskar** [comment]
No, the database creation and functioning code are all included in the project, you just have to register your app to firebase console and add your google-services.json and change the Authorization key with your key from your firebase project.

**Comment by uditbhaskar** [comment]
Also in firebase Storage Rules, change value of "allow read, write:" from "if request.auth != null" to "if true".

**Comment by AjeetMakvana** [comment]
Please , tell me how to change the Authorization key with the firebase key ?

**Comment by uditbhaskar** [comment]
You need edit google-services.json file and rest you can search on web.

**Comment by AjeetMakvana** [comment]
Thanks a Lot.

Can i contact you anywhere else , 
Or just give your mail id.

So , i can contact for further queries.

**Comment by uditbhaskar** [comment]
You should try to find answers on the web.

**Comment by AjeetMakvana** [comment]
Okay
Thanks

It's an Awesome app.

**Comment by AjeetMakvana** [comment]
Can you send your Apk once.
